tasks:
  - name: GenerateSQLQuery
    description: "Convert user question into an SQL query using Gemini."
    agent: "QueryGeneratorAgent"
    inputs:
      - user_question
    outputs:
      - sql_query

  - name: FetchSalesData
    description: "Fetch sales data from SQL Server."
    agent: "DatabaseAgent"
    inputs:
      - sql_query
    outputs:
      - sales_data

  - name: GenerateInsights
    description: "Generate weekly and monthly sales insights."
    agent: "InsightsAgent"
    inputs:
      - sales_data
    outputs:
      - insights

  - name: SendEmail
    description: "Send insights via Outlook email."
    agent: "EmailAgent"
    inputs:
      - insights
    outputs:
      - email_status
